services:
  act-sdk_exec:
    image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
    tty: true
    restart: always
    ports:
      - "${GUI_FWD_PORT}:8002" # serverアプリとの通信
      - "${WSS_FWD_PORT}:5003" # Websocketとの通信
    environment:
      PYTHONPATH: /workspace/app-base/src:/workspace
    volumes:
      - workspace_app:/workspace/app
      - ./log:/workspace/app/exec/log
      - ./app_container/src:/workspace/app/src
      - ./app_container/configs:/workspace/app/exec/configs
      - ./add_components/websocket_sv:/workspace/app-base/src/app_base/parts/websocket_sv
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    entrypoint: "/bin/sh -c ' cd /workspace/app/src && python3 SampleApp.py '"
volumes:
  workspace_app: