Here is the equivalent Kubernetes manifest for the given Docker Compose file:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: act-sdk-exec
spec:
  containers:
  - name: act-sdk-exec
    image: registry/repository/main_exec_image
    tty: true
    ports:
    - containerPort: 8002
    - containerPort: 5003
    env:
    - name: PYTHONPATH
      value: /workspace/app-base/src:/workspace
    volumeMounts:
    - name: workspace-app
      mountPath: /workspace/app
    - name: log-volume
      mountPath: /workspace/app/exec/log
    - name: src-volume
      mountPath: /workspace/app/src
    - name: configs-volume
      mountPath: /workspace/app/exec/configs
    - name: websocket-sv-volume
      mountPath: /workspace/app-base/src/app_base/parts/websocket_sv
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
      seccompProfile: unconfined
    command: ["/bin/sh", "-c"]
    args: ["cd /workspace/app/src && python3 SampleApp.py"]
  volumes:
  - name: workspace-app
    emptyDir: {}
  - name: log-volume
    hostPath:
      path: /path/to/log
  - name: src-volume
    hostPath:
      path: /path/to/app_container/src
  - name: configs-volume
    hostPath:
      path: /path/to/app_container/configs
  - name: websocket-sv-volume
    hostPath:
      path: /path/to/add_components/websocket_sv
```

Please replace the placeholders like `registry`, `repository`, `main_exec_image`, and the host path directories (`/path/to/log`, `/path/to/app_container/src`, `/path/to/app_container/configs`, `/path/to/add_components/websocket_sv`) with the actual values in your environment. This Kubernetes manifest defines a Pod with a container that corresponds to the `act-sdk_exec` service in the Docker Compose file.