apiVersion: v1
kind: Pod
metadata:
  name: act-sdk-exec
spec:
  containers:
  - name: act-sdk-exec
    image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
    tty: true
    ports:
    - containerPort: 8002
    - containerPort: 5003
    env:
    - name: PYTHONPATH
      value: /workspace/app-base/src:/workspace
    volumeMounts:
    - name: workspace-app
      mountPath: /workspace/app
    - name: log
      mountPath: /workspace/app/exec/log
    - name: app-src
      mountPath: /workspace/app/src
    - name: app-configs
      mountPath: /workspace/app/exec/configs
    - name: websocket-sv
      mountPath: /workspace/app-base/src/app_base/parts/websocket_sv
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
      seccompProfile: unconfined
    command: ["/bin/sh", "-c"]
    args: ["cd /workspace/app/src && python3 SampleApp.py"]
  volumes:
  - name: workspace-app
  - name: log
    hostPath:
      path: /path/to/log
  - name: app-src
    hostPath:
      path: /path/to/app_container/src
  - name: app-configs
    hostPath:
      path: /path/to/app_container/configs
  - name: websocket-sv
    hostPath:
      path: /path/to/add_components/websocket_sv
```