apiVersion: v1
kind: Service
metadata:
  name: act-sdk-exec
spec:
  selector:
    app: act-sdk-exec
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
    - protocol: TCP
      port: 5003
      targetPort: 5003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-sdk-exec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-sdk-exec
  template:
    metadata:
      labels:
        app: act-sdk-exec
    spec:
      containers:
        - name: act-sdk-exec
          image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
          ports:
            - containerPort: 8002
            - containerPort: 5003
          env:
            - name: PYTHONPATH
              value: /workspace/app-base/src:/workspace
          volumeMounts:
            - mountPath: /workspace/app
              name: workspace-app
            - mountPath: /workspace/app/exec/log
              name: log-volume
            - mountPath: /workspace/app/src
              name: app-container-src
            - mountPath: /workspace/app/exec/configs
              name: app-container-configs
            - mountPath: /workspace/app-base/src/app_base/parts/websocket_sv
              name: websocket-sv
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            seccompProfile:
              type: Unconfined
          command: ["/bin/sh", "-c", "cd /workspace/app/src && python3 SampleApp.py"]
      volumes:
        - name: workspace-app
          persistentVolumeClaim:
            claimName: workspace-app
        - name: log-volume
          hostPath:
            path: ./log
        - name: app-container-src
          hostPath:
            path: ./app_container/src
        - name: app-container-configs
          hostPath:
            path: ./app_container/configs
        - name: websocket-sv
          hostPath:
            path: ./add_components/websocket_sv