apiVersion: v1
kind: Pod
metadata:
  name: act-sdk-exec
spec:
  containers:
  - name: act-sdk-exec
    image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
    tty: true
    ports:
      - containerPort: 8002
        hostPort: ${GUI_FWD_PORT}
      - containerPort: 5003
        hostPort: ${WSS_FWD_PORT}
    env:
      - name: PYTHONPATH
        value: /workspace/app-base/src:/workspace
    volumeMounts:
      - name: workspace-app
        mountPath: /workspace/app
      - name: log
        mountPath: /workspace/app/exec/log
      - name: app-src
        mountPath: /workspace/app/src
      - name: app-configs
        mountPath: /workspace/app/exec/configs
      - name: websocket-sv
        mountPath: /workspace/app-base/src/app_base/parts/websocket_sv
    securityContext:
      capabilities:
        add:
          - SYS_ADMIN
      seccompProfile: unconfined
    command: ["/bin/sh", "-c", "cd /workspace/app/src && python3 SampleApp.py"]
  volumes:
    - name: workspace-app
      emptyDir: {}
    - name: log
      hostPath:
        path: /workspace/app/exec/log
    - name: app-src
      hostPath:
        path: /app_container/src
    - name: app-configs
      hostPath:
        path: /app_container/configs
    - name: websocket-sv
      hostPath:
        path: /add_components/websocket_sv
    restartPolicy: Always