apiVersion: v1
kind: Service
metadata:
  name: act-sdk-exec
spec:
  selector:
    app: act-sdk-exec
  ports:
    - name: server-port
      port: 8002
      targetPort: 8002
    - name: websocket-port
      port: 5003
      targetPort: 5003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-sdk-exec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-sdk-exec
  template:
    metadata:
      labels:
        app: act-sdk-exec
    spec:
      containers:
        - name: act-sdk-exec
          image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
          ports:
            - containerPort: 8002
            - containerPort: 5003
          env:
            - name: PYTHONPATH
              value: /workspace/app-base/src:/workspace
          volumeMounts:
            - name: workspace-app
              mountPath: /workspace/app
            - name: log-volume
              mountPath: /workspace/app/exec/log
            - name: src-volume
              mountPath: /workspace/app/src
            - name: configs-volume
              mountPath: /workspace/app/exec/configs
            - name: websocket-sv-volume
              mountPath: /workspace/app-base/src/app_base/parts/websocket_sv
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            seccompProfile: unconfined
          command: ["/bin/sh", "-c", "cd /workspace/app/src && python3 SampleApp.py"]
      volumes:
        - name: workspace-app
          emptyDir: {}
        - name: log-volume
          hostPath:
            path: ./log
        - name: src-volume
          hostPath:
            path: ./app_container/src
        - name: configs-volume
          hostPath:
            path: ./app_container/configs
        - name: websocket-sv-volume
          hostPath:
            path: ./add_components/websocket_sv