Here is the equivalent Kubernetes manifest for the given Docker Compose service:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: act-sdk-exec
spec:
  containers:
  - name: act-sdk-exec
    image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
    tty: true
    ports:
    - containerPort: 8002
    - containerPort: 5003
    env:
    - name: PYTHONPATH
      value: /workspace/app-base/src:/workspace
    volumeMounts:
    - mountPath: /workspace/app
      name: workspace-app
    - mountPath: /workspace/app/exec/log
      name: workspace-app
    - mountPath: /workspace/app/src
      name: workspace-app
    - mountPath: /workspace/app/exec/configs
      name: workspace-app
    - mountPath: /workspace/app-base/src/app_base/parts/websocket_sv
      name: workspace-app
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
      seccompProfile: unconfined
    command: ["/bin/sh", "-c"]
    args: ["cd /workspace/app/src && python3 SampleApp.py"]
  volumes:
  - name: workspace-app
    emptyDir: {}
```

Please note that this manifest creates a Pod in Kubernetes, which is similar to a Docker container. You may need to adjust the manifest based on your specific Kubernetes setup and requirements.