apiVersion: v1
kind: Service
metadata:
  name: act-sdk-exec
spec:
  selector:
    app: act-sdk-exec
  ports:
    - name: gui-fwd-port
      port: 8002
      targetPort: 8002
    - name: wss-fwd-port
      port: 5003
      targetPort: 5003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-sdk-exec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-sdk-exec
  template:
    metadata:
      labels:
        app: act-sdk-exec
    spec:
      containers:
        - name: act-sdk-exec
          image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
          tty: true
          ports:
            - containerPort: 8002
            - containerPort: 5003
          env:
            - name: PYTHONPATH
              value: /workspace/app-base/src:/workspace
          volumeMounts:
            - name: workspace-app
              mountPath: /workspace/app
            - name: log
              mountPath: /workspace/app/exec/log
            - name: app-src
              mountPath: /workspace/app/src
            - name: app-configs
              mountPath: /workspace/app/exec/configs
            - name: websocket-sv
              mountPath: /workspace/app-base/src/app_base/parts/websocket_sv
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            seccompProfile:
              type: unconfined
          command: ["/bin/sh", "-c", "cd /workspace/app/src && python3 SampleApp.py"]
      volumes:
        - name: workspace-app
          emptyDir: {}
        - name: log
          hostPath:
            path: /log
        - name: app-src
          hostPath:
            path: /app_container/src
        - name: app-configs
          hostPath:
            path: /app_container/configs
        - name: websocket-sv
          hostPath:
            path: /add_components/websocket_sv