services:
  postgres:
    image: postgres
    restart: always
    tty: true
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 10s
volumes:
  pgsql-data:
