services:
  act-sdk_app:
    build:
      context: .
      dockerfile: app_container/Dockerfile
    image: ${REGISTRY}/${REPOSITORY}/${MAIN_SOURCE_IMAGE}
    restart: always
    tty: true
    volumes:
      - workspace_app:/workspace/app
  act-sdk_exec:
    build:
      context: .
      dockerfile: exec_container/Dockerfile
      target: ${ARCH}_stage
      args:
        USER: ${USER}
        GROUP: ${GROUP}
        UID: ${EXEC_UID}
        GID: ${EXEC_GID}
    image: ${REGISTRY}/${REPOSITORY}/${MAIN_EXEC_IMAGE}
    tty: true
    restart: always
    ports:
      - "${GUI_FWD_PORT}:8002" # serverアプリとの通信
      - "${WSS_FWD_PORT}:5003" # Websocketとの通信
    depends_on:
      - act-sdk_app
    environment:
      PYTHONPATH: /workspace/app-base/src:/workspace
    volumes:
      - workspace_app:/workspace/app
      - ./log:/workspace/app/exec/log
      - ./app_container/src:/workspace/app/src
      - ./app_container/app-base:/workspace/app-base
      - ./app_container/actlyzer:/workspace/actlyzer
      - ./app_container/configs:/workspace/app/exec/configs
      - ./add_components/websocket_sv:/workspace/app-base/src/app_base/parts/websocket_sv
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    entrypoint: "/bin/sh -c ' cd /workspace/app/src && python3 SampleApp.py '"
volumes:
  workspace_app:
